# Generated by Django 3.0.5 on 2021-04-12 16:19

from django.db import migrations, models
import djongo.models.fields
import kitchen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('mobileno', models.TextField(blank=True, null=True)),
                ('location', djongo.models.fields.EmbeddedField(model_container=kitchen.models.Location)),
            ],
        ),
    ]
